"""Add links column to DailySummary

Revision ID: d6e9b993464d
Revises: 
Create Date: 2024-04-03 20:23:59.869121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd6e9b993464d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_summary', schema=None) as batch_op:
        batch_op.add_column(sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_summary', schema=None) as batch_op:
        batch_op.drop_column('links')

    # ### end Alembic commands ###
